on: [workflow_dispatch]

name: Build bun runtime

jobs:
  build-cli:
    permissions:
      packages: write
    strategy:
      matrix:
        version:
          - bun: 1.0
            nots-worker: 0
            tags: |
              ghcr.io/nots-dev/runtime-bun:latest
              ghcr.io/nots-dev/runtime-bun:1
              ghcr.io/nots-dev/runtime-bun:1.0

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ matrix.version.tags }}
          platforms: linux/amd64,linux/arm64
          file: runtime/bun/Dockerfile
          build-args: |
            NOTS_WORKER_VERSION=${{ matrix.version.nots-worker }}
            BUN_VERSION=1.0
