on: [workflow_dispatch]

name: Build node.js runtime

jobs:
  node:
    permissions:
      packages: write
    strategy:
      matrix:
        version:
          - node: 20
            nots-worker: 0
            tags: |
              ghcr.io/nots-dev/runtime-node:lts
              ghcr.io/nots-dev/runtime-node:20
          - node: 21
            nots-worker: 0
            tags: |
              ghcr.io/nots-dev/runtime-node:latest
              ghcr.io/nots-dev/runtime-node:21

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ matrix.version.tags }}
          platforms: linux/amd64,linux/arm64
          file: runtime/node/Dockerfile
          context: /tmp/outputs
          build-args: |
            NOTS_WORKER_VERSION=${{ matrix.version.nots-worker }}
